/* Generated by Yosys 0.46+11 (git sha1 0200a7680, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

module PointerChasingFSM(clock, reset, io_start, io_done, \io_final_addr[0] , \io_final_addr[1] , \io_final_addr[2] , \io_final_addr[3] );
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire \_chaser_io_sram_rd_addr[0] ;
  wire \_chaser_io_sram_rd_addr[1] ;
  wire \chaser._GEN ;
  wire \chaser._GEN_0 ;
  wire \chaser.clock ;
  reg \chaser.currentAddr[0] ;
  reg \chaser.currentAddr[1] ;
  reg \chaser.currentAddr[2] ;
  reg \chaser.currentAddr[3] ;
  wire \chaser.io_done ;
  wire \chaser.io_final_addr[0] ;
  wire \chaser.io_final_addr[1] ;
  wire \chaser.io_final_addr[2] ;
  wire \chaser.io_final_addr[3] ;
  wire \chaser.io_sram_rd_addr[0] ;
  wire \chaser.io_sram_rd_addr[1] ;
  wire \chaser.reset ;
  reg \chaser.state[0] ;
  reg \chaser.state[1] ;
  reg \chaser.state[2] ;
  reg \chaser.step[0] ;
  reg \chaser.step[1] ;
  reg \chaser.step[2] ;
  input clock;
  wire clock;
  reg \initCntr[0] ;
  reg \initCntr[1] ;
  reg \initCntr[2] ;
  reg \initCntr[3] ;
  reg initDone;
  output io_done;
  wire io_done;
  output \io_final_addr[0] ;
  wire \io_final_addr[0] ;
  output \io_final_addr[1] ;
  wire \io_final_addr[1] ;
  output \io_final_addr[2] ;
  wire \io_final_addr[2] ;
  output \io_final_addr[3] ;
  wire \io_final_addr[3] ;
  input io_start;
  wire io_start;
  input reset;
  wire reset;
  wire \sram.clock ;
  wire \sram.io_rd_addr[0] ;
  wire \sram.io_rd_addr[1] ;
  wire \sram.io_rd_addr[2] ;
  wire \sram.io_wr_addr[0] ;
  wire \sram.io_wr_addr[1] ;
  wire \sram.io_wr_addr[2] ;
  reg \sram.mem_ext.Memory[0][0] ;
  reg \sram.mem_ext.Memory[0][1] ;
  reg \sram.mem_ext.Memory[0][2] ;
  reg \sram.mem_ext.Memory[0][3] ;
  reg \sram.mem_ext.Memory[1][0] ;
  reg \sram.mem_ext.Memory[1][1] ;
  reg \sram.mem_ext.Memory[1][2] ;
  reg \sram.mem_ext.Memory[1][3] ;
  reg \sram.mem_ext.Memory[2][0] ;
  reg \sram.mem_ext.Memory[2][1] ;
  reg \sram.mem_ext.Memory[2][2] ;
  reg \sram.mem_ext.Memory[2][3] ;
  reg \sram.mem_ext.Memory[3][0] ;
  reg \sram.mem_ext.Memory[3][1] ;
  reg \sram.mem_ext.Memory[3][2] ;
  reg \sram.mem_ext.Memory[3][3] ;
  reg \sram.mem_ext.Memory[4][0] ;
  reg \sram.mem_ext.Memory[4][1] ;
  reg \sram.mem_ext.Memory[4][2] ;
  reg \sram.mem_ext.Memory[4][3] ;
  reg \sram.mem_ext.Memory[5][0] ;
  reg \sram.mem_ext.Memory[5][1] ;
  reg \sram.mem_ext.Memory[5][2] ;
  reg \sram.mem_ext.Memory[5][3] ;
  reg \sram.mem_ext.Memory[6][0] ;
  reg \sram.mem_ext.Memory[6][1] ;
  reg \sram.mem_ext.Memory[6][2] ;
  reg \sram.mem_ext.Memory[6][3] ;
  reg \sram.mem_ext.Memory[7][0] ;
  reg \sram.mem_ext.Memory[7][1] ;
  reg \sram.mem_ext.Memory[7][2] ;
  reg \sram.mem_ext.Memory[7][3] ;
  wire \sram.mem_ext.R0_addr[0] ;
  wire \sram.mem_ext.R0_addr[1] ;
  wire \sram.mem_ext.R0_addr[2] ;
  wire \sram.mem_ext.R0_clk ;
  wire \sram.mem_ext.R0_en ;
  wire \sram.mem_ext.W0_addr[0] ;
  wire \sram.mem_ext.W0_addr[1] ;
  wire \sram.mem_ext.W0_addr[2] ;
  wire \sram.mem_ext.W0_clk ;
  reg \sram.mem_ext._R0_addr_d0[0] ;
  reg \sram.mem_ext._R0_addr_d0[1] ;
  wire \sram.mem_ext._R0_addr_d0[2] ;
  wire \sram.mem_ext._R0_en_d0 ;
  always @(posedge clock)
    initDone <= _004_;
  always @(posedge clock)
    \initCntr[0]  <= _000_;
  always @(posedge clock)
    \initCntr[1]  <= _001_;
  always @(posedge clock)
    \initCntr[2]  <= _002_;
  always @(posedge clock)
    \initCntr[3]  <= _003_;
  always @(posedge clock)
    \chaser.state[0]  <= _012_;
  always @(posedge clock)
    \chaser.state[1]  <= _013_;
  always @(posedge clock)
    \chaser.state[2]  <= _014_;
  always @(posedge clock)
    \chaser.currentAddr[0]  <= _005_;
  always @(posedge clock)
    \chaser.currentAddr[1]  <= _006_;
  always @(posedge clock)
    \chaser.currentAddr[2]  <= _007_;
  always @(posedge clock)
    \chaser.currentAddr[3]  <= _008_;
  always @(posedge clock)
    \chaser.step[0]  <= _009_;
  always @(posedge clock)
    \chaser.step[1]  <= _010_;
  always @(posedge clock)
    \chaser.step[2]  <= _011_;
  always @(posedge clock)
    \sram.mem_ext.Memory[5][0]  <= _035_;
  always @(posedge clock)
    \sram.mem_ext.Memory[5][1]  <= _036_;
  always @(posedge clock)
    \sram.mem_ext.Memory[5][2]  <= _037_;
  always @(posedge clock)
    \sram.mem_ext.Memory[5][3]  <= _038_;
  always @(posedge clock)
    \sram.mem_ext.Memory[4][0]  <= _031_;
  always @(posedge clock)
    \sram.mem_ext.Memory[4][1]  <= _032_;
  always @(posedge clock)
    \sram.mem_ext.Memory[4][2]  <= _033_;
  always @(posedge clock)
    \sram.mem_ext.Memory[4][3]  <= _034_;
  always @(posedge clock)
    \sram.mem_ext.Memory[3][0]  <= _027_;
  always @(posedge clock)
    \sram.mem_ext.Memory[3][1]  <= _028_;
  always @(posedge clock)
    \sram.mem_ext.Memory[3][2]  <= _029_;
  always @(posedge clock)
    \sram.mem_ext.Memory[3][3]  <= _030_;
  always @(posedge clock)
    \sram.mem_ext.Memory[7][0]  <= _043_;
  always @(posedge clock)
    \sram.mem_ext.Memory[7][1]  <= _044_;
  always @(posedge clock)
    \sram.mem_ext.Memory[7][2]  <= _045_;
  always @(posedge clock)
    \sram.mem_ext.Memory[7][3]  <= _046_;
  always @(posedge clock)
    \sram.mem_ext.Memory[2][0]  <= _023_;
  always @(posedge clock)
    \sram.mem_ext.Memory[2][1]  <= _024_;
  always @(posedge clock)
    \sram.mem_ext.Memory[2][2]  <= _025_;
  always @(posedge clock)
    \sram.mem_ext.Memory[2][3]  <= _026_;
  always @(posedge clock)
    \sram.mem_ext.Memory[1][0]  <= _019_;
  always @(posedge clock)
    \sram.mem_ext.Memory[1][1]  <= _020_;
  always @(posedge clock)
    \sram.mem_ext.Memory[1][2]  <= _021_;
  always @(posedge clock)
    \sram.mem_ext.Memory[1][3]  <= _022_;
  always @(posedge clock)
    \sram.mem_ext.Memory[6][0]  <= _039_;
  always @(posedge clock)
    \sram.mem_ext.Memory[6][1]  <= _040_;
  always @(posedge clock)
    \sram.mem_ext.Memory[6][2]  <= _041_;
  always @(posedge clock)
    \sram.mem_ext.Memory[6][3]  <= _042_;
  always @(posedge clock)
    \sram.mem_ext._R0_addr_d0[0]  <= \sram.mem_ext.R0_addr[0] ;
  always @(posedge clock)
    \sram.mem_ext._R0_addr_d0[1]  <= \sram.mem_ext.R0_addr[1] ;
  always @(posedge clock)
    \sram.mem_ext.Memory[0][0]  <= _015_;
  always @(posedge clock)
    \sram.mem_ext.Memory[0][1]  <= _016_;
  always @(posedge clock)
    \sram.mem_ext.Memory[0][2]  <= _017_;
  always @(posedge clock)
    \sram.mem_ext.Memory[0][3]  <= _018_;
  assign _008_ = 8'hb1 >> { _057_, _047_, \chaser.state[0]  };
  assign _055_ = 8'h27 >> { \sram.mem_ext.Memory[6][3] , \sram.mem_ext.Memory[7][3] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _035_ = 8'hd8 >> { \sram.mem_ext.Memory[5][0] , _103_, _115_ };
  assign _115_ = 8'h08 >> { initDone, \initCntr[0] , _114_ };
  assign _036_ = 8'hd8 >> { \sram.mem_ext.Memory[5][1] , _104_, _115_ };
  assign _037_ = 8'hd8 >> { \sram.mem_ext.Memory[5][2] , _105_, _115_ };
  assign _038_ = 8'hd8 >> { \sram.mem_ext.Memory[5][3] , _107_, _115_ };
  assign _039_ = 8'hd8 >> { \sram.mem_ext.Memory[6][0] , _103_, _116_ };
  assign _116_ = 8'h02 >> { \initCntr[0] , initDone, _117_ };
  assign _117_ = 8'h08 >> { initDone, \initCntr[2] , \initCntr[1]  };
  assign _040_ = 8'hd8 >> { \sram.mem_ext.Memory[6][1] , _104_, _116_ };
  assign _041_ = 8'hd8 >> { \sram.mem_ext.Memory[6][2] , _105_, _116_ };
  assign _056_ = 4'h2 >> { \chaser.step[2] , \chaser.state[2]  };
  assign _042_ = 8'hd8 >> { \sram.mem_ext.Memory[6][3] , _107_, _116_ };
  assign _043_ = 8'hd8 >> { \sram.mem_ext.Memory[7][0] , _103_, _118_ };
  assign _118_ = 8'h08 >> { initDone, \initCntr[0] , _117_ };
  assign _044_ = 8'hd8 >> { \sram.mem_ext.Memory[7][1] , _104_, _118_ };
  assign _045_ = 8'hd8 >> { \sram.mem_ext.Memory[7][2] , _105_, _118_ };
  assign _046_ = 8'hd8 >> { \sram.mem_ext.Memory[7][3] , _107_, _118_ };
  assign _002_ = 4'h1 >> { _119_, reset };
  assign _119_ = 8'h15 >> { initDone, \initCntr[2] , _105_ };
  assign _001_ = 4'h1 >> { _120_, reset };
  assign _120_ = 8'h59 >> { initDone, \initCntr[0] , \initCntr[1]  };
  assign _057_ = 4'h2 >> { _058_, \chaser.currentAddr[3]  };
  assign _000_ = 8'h09 >> { reset, \initCntr[0] , initDone };
  assign _004_ = 8'h54 >> { initDone, _121_, reset };
  assign _121_ = 8'h08 >> { \initCntr[3] , \initCntr[2] , _106_ };
  assign _003_ = 4'h1 >> { _122_, reset };
  assign _122_ = 8'h15 >> { initDone, \initCntr[3] , _107_ };
  assign \sram.mem_ext.R0_addr[1]  = 8'h08 >> { \chaser.state[0] , _056_, \chaser.currentAddr[1]  };
  assign _058_ = 4'h8 >> { initDone, io_start };
  assign _011_ = 4'h1 >> { _059_, reset };
  assign _059_ = 8'h4e >> { _062_, _060_, \chaser.state[0]  };
  assign _060_ = 8'h15 >> { \chaser.state[2] , _061_, \chaser.step[2]  };
  assign _061_ = 4'h8 >> { \chaser.step[0] , \chaser.step[1]  };
  assign _062_ = 4'h2 >> { _058_, \chaser.step[2]  };
  assign _014_ = 8'hea >> { _063_, \chaser.state[0] , _064_ };
  assign _047_ = 8'h27 >> { \chaser.currentAddr[3] , _048_, _056_ };
  assign _063_ = 4'h2 >> { reset, _058_ };
  assign _064_ = 8'h02 >> { reset, \chaser.step[2] , \chaser.state[2]  };
  assign _012_ = 8'hae >> { _058_, \chaser.state[0] , reset };
  assign _013_ = 8'hae >> { reset, \chaser.state[1] , _065_ };
  assign _065_ = 8'h08 >> { reset, \chaser.step[2] , \chaser.state[2]  };
  assign \sram.mem_ext.R0_addr[0]  = 8'h08 >> { \chaser.state[0] , _056_, \chaser.currentAddr[0]  };
  assign _009_ = 8'h54 >> { _067_, _066_, reset };
  assign _066_ = 8'h06 >> { \chaser.state[0] , _056_, \chaser.step[0]  };
  assign _067_ = 8'h08 >> { _058_, \chaser.state[0] , \chaser.step[0]  };
  assign _010_ = 4'h1 >> { _068_, reset };
  assign _048_ = 4'h2 >> { _049_, _124_ };
  assign _068_ = 8'h4e >> { _070_, _069_, \chaser.state[0]  };
  assign _069_ = 8'h95 >> { _056_, \chaser.step[0] , \chaser.step[1]  };
  assign _070_ = 4'h2 >> { _058_, \chaser.step[1]  };
  assign _005_ = 8'hb1 >> { _080_, _071_, \chaser.state[0]  };
  assign _071_ = 8'h27 >> { \chaser.currentAddr[0] , _072_, _056_ };
  assign _072_ = 4'h2 >> { _073_, _124_ };
  assign _073_ = 8'he4 >> { _077_, _074_, _123_ };
  assign _074_ = 8'he4 >> { _076_, _075_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _075_ = 8'h27 >> { \sram.mem_ext.Memory[0][0] , \sram.mem_ext.Memory[1][0] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _076_ = 8'h27 >> { \sram.mem_ext.Memory[2][0] , \sram.mem_ext.Memory[3][0] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _049_ = 8'he4 >> { _053_, _050_, _123_ };
  assign _077_ = 8'he4 >> { _079_, _078_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _078_ = 8'h27 >> { \sram.mem_ext.Memory[4][0] , \sram.mem_ext.Memory[5][0] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _079_ = 8'h27 >> { \sram.mem_ext.Memory[6][0] , \sram.mem_ext.Memory[7][0] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _080_ = 4'h2 >> { _058_, \chaser.currentAddr[0]  };
  assign _006_ = 8'hb1 >> { _090_, _081_, \chaser.state[0]  };
  assign _081_ = 8'h27 >> { \chaser.currentAddr[1] , _082_, _056_ };
  assign _082_ = 4'h2 >> { _083_, _124_ };
  assign _083_ = 8'he4 >> { _087_, _084_, _123_ };
  assign _084_ = 8'he4 >> { _086_, _085_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _085_ = 8'h27 >> { \sram.mem_ext.Memory[0][1] , \sram.mem_ext.Memory[1][1] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _050_ = 8'he4 >> { _052_, _051_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _086_ = 8'h27 >> { \sram.mem_ext.Memory[2][1] , \sram.mem_ext.Memory[3][1] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _087_ = 8'he4 >> { _089_, _088_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _088_ = 8'h27 >> { \sram.mem_ext.Memory[4][1] , \sram.mem_ext.Memory[5][1] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _089_ = 8'h27 >> { \sram.mem_ext.Memory[6][1] , \sram.mem_ext.Memory[7][1] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _090_ = 4'h2 >> { _058_, \chaser.currentAddr[1]  };
  assign _007_ = 8'hb1 >> { _100_, _091_, \chaser.state[0]  };
  assign _091_ = 8'h27 >> { \chaser.currentAddr[2] , _092_, _056_ };
  assign _092_ = 4'h2 >> { _093_, _124_ };
  assign _093_ = 8'he4 >> { _097_, _094_, _123_ };
  assign _094_ = 8'he4 >> { _096_, _095_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _051_ = 8'h27 >> { \sram.mem_ext.Memory[0][3] , \sram.mem_ext.Memory[1][3] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _095_ = 8'h1b >> { \sram.mem_ext.Memory[1][2] , \sram.mem_ext.Memory[0][2] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _096_ = 8'h27 >> { \sram.mem_ext.Memory[2][2] , \sram.mem_ext.Memory[3][2] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _097_ = 8'he4 >> { _099_, _098_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _098_ = 8'h27 >> { \sram.mem_ext.Memory[4][2] , \sram.mem_ext.Memory[5][2] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _099_ = 8'h27 >> { \sram.mem_ext.Memory[6][2] , \sram.mem_ext.Memory[7][2] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _100_ = 4'h2 >> { _058_, \chaser.currentAddr[2]  };
  assign _015_ = 8'hd8 >> { \sram.mem_ext.Memory[0][0] , _103_, _101_ };
  assign _101_ = 8'h02 >> { \initCntr[0] , initDone, _102_ };
  assign _102_ = 8'hab >> { \initCntr[2] , \initCntr[1] , initDone };
  assign _103_ = 4'h1 >> { \initCntr[0] , initDone };
  assign _052_ = 8'h27 >> { \sram.mem_ext.Memory[2][3] , \sram.mem_ext.Memory[3][3] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _016_ = 8'hd8 >> { \sram.mem_ext.Memory[0][1] , _104_, _101_ };
  assign _104_ = 8'h06 >> { initDone, \initCntr[1] , \initCntr[0]  };
  assign _017_ = 8'hd8 >> { \sram.mem_ext.Memory[0][2] , _105_, _101_ };
  assign _105_ = 8'h06 >> { initDone, _106_, \initCntr[2]  };
  assign _106_ = 4'h8 >> { \initCntr[1] , \initCntr[0]  };
  assign _018_ = 8'hd8 >> { \sram.mem_ext.Memory[0][3] , _107_, _101_ };
  assign _107_ = 8'h06 >> { initDone, _108_, \initCntr[3]  };
  assign _108_ = 4'h8 >> { _106_, \initCntr[2]  };
  assign _019_ = 8'hd8 >> { \sram.mem_ext.Memory[1][0] , _103_, _109_ };
  assign _109_ = 8'h08 >> { initDone, \initCntr[0] , _102_ };
  assign _053_ = 8'he4 >> { _055_, _054_, \sram.mem_ext._R0_addr_d0[1]  };
  assign _020_ = 8'hd8 >> { \sram.mem_ext.Memory[1][1] , _104_, _109_ };
  assign _021_ = 8'hd8 >> { \sram.mem_ext.Memory[1][2] , _105_, _109_ };
  assign _022_ = 8'hd8 >> { \sram.mem_ext.Memory[1][3] , _107_, _109_ };
  assign _023_ = 8'hd8 >> { \sram.mem_ext.Memory[2][0] , _103_, _110_ };
  assign _110_ = 8'h02 >> { \initCntr[0] , initDone, _111_ };
  assign _111_ = 8'h02 >> { \initCntr[2] , initDone, \initCntr[1]  };
  assign _024_ = 8'hd8 >> { \sram.mem_ext.Memory[2][1] , _104_, _110_ };
  assign _025_ = 8'hd8 >> { \sram.mem_ext.Memory[2][2] , _105_, _110_ };
  assign _026_ = 8'hd8 >> { \sram.mem_ext.Memory[2][3] , _107_, _110_ };
  assign _027_ = 8'hd8 >> { \sram.mem_ext.Memory[3][0] , _103_, _112_ };
  assign _054_ = 8'h27 >> { \sram.mem_ext.Memory[4][3] , \sram.mem_ext.Memory[5][3] , \sram.mem_ext._R0_addr_d0[0]  };
  assign _112_ = 8'h08 >> { initDone, \initCntr[0] , _111_ };
  assign _028_ = 8'hd8 >> { \sram.mem_ext.Memory[3][1] , _104_, _112_ };
  assign _029_ = 8'hd8 >> { \sram.mem_ext.Memory[3][2] , _105_, _112_ };
  assign _030_ = 8'hd8 >> { \sram.mem_ext.Memory[3][3] , _107_, _112_ };
  assign _031_ = 8'hd8 >> { \sram.mem_ext.Memory[4][0] , _103_, _113_ };
  assign _113_ = 8'h02 >> { \initCntr[0] , initDone, _114_ };
  assign _114_ = 8'h02 >> { \initCntr[1] , initDone, \initCntr[2]  };
  assign _032_ = 8'hd8 >> { \sram.mem_ext.Memory[4][1] , _104_, _113_ };
  assign _033_ = 8'hd8 >> { \sram.mem_ext.Memory[4][2] , _105_, _113_ };
  assign _034_ = 8'hd8 >> { \sram.mem_ext.Memory[4][3] , _107_, _113_ };
  assign _123_ = 1'h0;
  assign _124_ = 1'h1;
  assign _125_ = 1'hx;
  assign \sram.mem_ext._R0_en_d0  = _124_;
  assign \sram.mem_ext._R0_addr_d0[2]  = _123_;
  assign \sram.mem_ext.W0_clk  = clock;
  assign \sram.mem_ext.W0_addr[2]  = \initCntr[2] ;
  assign \sram.mem_ext.W0_addr[1]  = \initCntr[1] ;
  assign \sram.mem_ext.W0_addr[0]  = \initCntr[0] ;
  assign \sram.mem_ext.R0_en  = _124_;
  assign \sram.mem_ext.R0_clk  = clock;
  assign \sram.mem_ext.R0_addr[2]  = _123_;
  assign \sram.io_wr_addr[2]  = \initCntr[2] ;
  assign \sram.io_wr_addr[1]  = \initCntr[1] ;
  assign \sram.io_wr_addr[0]  = \initCntr[0] ;
  assign \sram.io_rd_addr[2]  = _123_;
  assign \sram.io_rd_addr[1]  = \sram.mem_ext.R0_addr[1] ;
  assign \sram.io_rd_addr[0]  = \sram.mem_ext.R0_addr[0] ;
  assign \sram.clock  = clock;
  assign \io_final_addr[3]  = \chaser.currentAddr[3] ;
  assign \io_final_addr[2]  = \chaser.currentAddr[2] ;
  assign \io_final_addr[1]  = \chaser.currentAddr[1] ;
  assign \io_final_addr[0]  = \chaser.currentAddr[0] ;
  assign io_done = \chaser.state[1] ;
  assign \chaser.reset  = reset;
  assign \chaser.io_sram_rd_addr[1]  = \sram.mem_ext.R0_addr[1] ;
  assign \chaser.io_sram_rd_addr[0]  = \sram.mem_ext.R0_addr[0] ;
  assign \chaser.io_final_addr[3]  = \chaser.currentAddr[3] ;
  assign \chaser.io_final_addr[2]  = \chaser.currentAddr[2] ;
  assign \chaser.io_final_addr[1]  = \chaser.currentAddr[1] ;
  assign \chaser.io_final_addr[0]  = \chaser.currentAddr[0] ;
  assign \chaser.io_done  = \chaser.state[1] ;
  assign \chaser.clock  = clock;
  assign \chaser._GEN_0  = \chaser.state[2] ;
  assign \chaser._GEN  = \chaser.state[0] ;
  assign \_chaser_io_sram_rd_addr[1]  = \sram.mem_ext.R0_addr[1] ;
  assign \_chaser_io_sram_rd_addr[0]  = \sram.mem_ext.R0_addr[0] ;
endmodule
